ALTER TABLE tests
ADD COLUMN IF NOT EXISTS notify_on_failure BOOLEAN DEFAULT true,
ADD COLUMN IF NOT EXISTS notify_on_success BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS notification_channels VARCHAR(255)[] DEFAULT '{EMAIL}',
ADD COLUMN IF NOT EXISTS notification_recipients VARCHAR(255)[] DEFAULT '{}';