package com.company.qa.model.agent;

import com.company.qa.model.enums.AgentActionType;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.Map;

/**
 * Agent's plan for the next action.
 *
 * Generated by asking AI: "Given current context, what should I do next?"
 *
 * The AI returns:
 * - Which action to take
 * - Parameters for that action
 * - Reasoning for why this action makes sense
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class AgentPlan {

    /**
     * What action to take next.
     */
    private AgentActionType nextAction;

    /**
     * Parameters for the action.
     *
     * Example for GENERATE_TEST_CODE:
     * - jiraKey: "PROJ-123"
     * - testType: "UI"
     * - framework: "PLAYWRIGHT"
     *
     * Example for EXECUTE_TEST:
     * - testCode: "..." (generated code)
     * - retryOnFailure: true
     */
    private Map<String, Object> actionParameters;

    /**
     * AI's reasoning for choosing this action.
     *
     * Example:
     * "Based on the JIRA story requirements, I will generate a Playwright
     *  test that covers login functionality using role-based locators."
     */
    private String reasoning;

    /**
     * Expected outcome of this action.
     *
     * Example:
     * "Test code generated with proper Page Object references"
     */
    private String expectedOutcome;

    /**
     * Confidence level (0.0 to 1.0).
     *
     * Used to decide if action needs approval.
     */
    private Double confidence;

    /**
     * Does this plan require human approval before execution?
     */
    private boolean requiresApproval;

    /**
     * Get action parameter by key.
     */
    @SuppressWarnings("unchecked")
    public <T> T getParameter(String key, Class<T> type) {
        Object value = actionParameters.get(key);
        if (value == null) {
            return null;
        }
        return (T) value;
    }
}